a = SoundFile.new;
a.openRead("C:\\Users\\piert\\Music\\To Edit\\Anmon - Anmon - Tuvan 1.ogg");
a.openRead("C:\\Users\\piert\\Music\\Samples\\sample-1.ogg");
a.openRead("C:\\Users\\piert\\Music\\ZSpotify Music\\Party Inspiration\\Brian Eno, Rick Holland - the airman.ogg")
a.openRead(p);
p = "C:\\Users\\piert\\MakingMusic\\Samples\\Audacity\\By Movie\\Welcome To Chippendales\\WelcomeToChippendalesS01E05_WhySoBeige.wav";
a.inspect
e = Event.new;
a.cue(e);
e.play;
e.pause;